import Workout from 'src/helpers/CreateWorkout';

let workoutsByDate = [
    Workout(2022, 7, 3, 'Bears'),
    Workout(2022, 7, 2, 'Bears'),
    Workout(2022, 7, 1, 'Bears', ['push', 'sit']),
    Workout(2022, 6, 26, 'Abacus'),
    Workout(2022, 6, 28, 'Piston', [
        'Kettlebell deadlift tempo 4-0-1',
        'Balance Trainer Chest Press Pulse',
        'Dumbbell Goblet Squat Tempo 4-0-1',
        'Suspension Trainer Nutral Grip Row Pulse',
        'Sandbag Box Overhead Step Ups',
        '10 x Russian Twist + 2 x Jackknives',
        'Flat Bench Dumbbell Tempo Fly 4-0-1',
        'Soft Box Single Leg Deadball Hip Thruster Pause',
        'Barbell Bent Over Row Underhand Grip Tempo 4-0-1',
        'Lateral Lunge Pause',
        'Ybell Double Bicep Curl Twist Center Grip',
        'Plank Rotation',
    ]),
    Workout(2022, 7, 4, 'Templars', [
        'Battle Ropes Power Slams Partnered',
        'Suspension Trainer Mountain Climber',
        'Bike Standing Partnered',
        'Soft Box Jump Partnered',
        'Plate Sumo Squat + Bicep Curl',
        'Bench Tricep Dips Partnered',
        'Gorilla Bounds',
        'Ladder Tail Whips Partnered',
        '5 x Deadball Slam + 2 x Prisoner Squat',
        'Power Band In and Out Jumps + High Puls',
        'Ybell Single Arm Snatch Partnered',
        '10 x High Knees + 2 x Inch Worms Partnered',
        'Ybell Sprawl Lateral Jump Partnered',
        '2 x Push Ups + 4 x Wide Mountain Climbers + 2 x Star Jumps Partnered',
    ]),
    Workout(2022, 7, 5, 'Lonestar', [
        'dumbbell swiss ball single arm press rotation',
        'barbell romanian deadlift single leg',
        'suspension trainer single arm row',
        'dumbbell lateral lunge pulse',
        'revo standing single arm shoulder press',
        'kettlebell box lateral step up',
        'push up tripod hold',
        'balance trainer single leg hip thruster hold + calf raise',
        'dumbbell single arm renegade row',
        'deadball staggered squat',
        'ybell single clean + lunge',
        'side plank knee crunch',
    ]),
    Workout(2022, 7, 6, 'Afterglow', [
        'kettlebell swing // jump squat',
        'deadball overhead slams // burpee hands off',
        'agility box hurdle jumps // speed sprawls',
        'ybell squat press under grip // prisoner squat',
        'frog squats // hand walks in and hand walks out',
        'step trainer shuffle // tuck jumps',
        'medicine ball plyo lunge + twist // reverse burpee',
        'plate snatch // plate squat hold + chest press',
        'mountain climber wide // yogy push up',
    ]),
    Workout(2022, 7, 7, 'Romans', [
        'dumbbell bench incline fly',
        'barbell bicep partials x 3',
        'barbell tricep extension',
        'chin up overhand grip',
        'dumbbell swiss ball chest press alternate arm',
        'revo double kneeling shoulder press',
        'ybell double pronated push up + alternate knee drivetop grip',
        'kettlebell upright row',
        'plate weighted sit up pullover',
    ]),
    Workout(2022, 7, 8, 'Tempest', [
        'speed squats // ybell single alternate clean + lunge // a steps // bike erg tempest target (250/350m)',
        'elbow crunches // kettlebell squat + upright row // dumbbell punches // rower tempest target (150/200m)',
        'straight arm crunch // deadball pick up and slams // star jumps // ski erg tempest target (100/150m)',
        'frog squats // barbell push press // ice skater // bench hops tempest target(20/40)',
        '10 x High knees + 2 inchworm',
        'Squat Jack in & out',
        'Wide mountain climbers',
        '10 x High knees + 2 inchworm',
        'Squat Jack in & out',
        'Wide mountain climbers',
        'Burpee',
    ]),
    Workout(2022, 7, 9, 'Trackstars', [
        'barbell front squat',
        'burpee',
        'high knees on the spot',
        'speed squats',
        'rower sprints',
        'dumbbell alternate snatch',
        'pushup',
        'bike sprints standing',
        'plyometric lunge',
        'sit up',
        'russian twist',
        'softbox jump alternating',
        'dumbbell renegade row',
        'deadball over head slams',
        'kettlebell swing',
        'fast feet sprawl',
        'revo single push press alternate partner at extension',
        'dumbbell curl + press alternating',
    ]),
    Workout(2022, 7, 10, 'Pegasus', [
        'kettlebell romanian deadlift',
        'dumbbell alternate arm shoulder press',
        'suspension trainer automic crunch',
        'deadball bear hug squat',
        'barbell lying tricep extension pause',
        'ybell double hammer curl + alternate reverse lunge center grip',
        'revo sit ups raise',
        'plate box overhead step up',
        'dumbbell floor press pulse',
        'revo zercher curtsey squat',
        'slides arm circle',
        'power band low rear delt fly',
        'push up',
        'butterfly sit ups',
        'alternate forward lunge',
    ]),
    Workout(2022, 7, 11, 'Templars', [
        'sandbag double clean fast feet sprawl',
        'bear crawls back and forward short partnered',
        'suspension trainer alternate arm row',
        'kettlebell goblet squat partnered',
        'balance trainer burpee + shoulder press partnered',
        'box prisoner squat jump',
        'burpee hands off partnered',
        'dumbbell alternate lunge and over head press partnered',
        'forward run + 2 x push up + backwards run partnered',
        'seal jacks',
        'bench hop partnered',
        'plate low to high woodchop',
        'step trainer low squat jumps partnered',
        'bike hover partnered',
    ]),
    Workout(2022, 7, 12, 'Piston', [
        'dumbbell romanian deadlift tempo 4-0-1',
        'push up tempo',
        'sandbag box shouldered reverse lunge to step up',
        'dumbbell reverse fly',
        'barbell over head hold reverse lunge',
        'medicine ball jackknife',
        'dumbbell incline bench press neutral grip pause',
        'step trainer single leg hip thruster pause',
        'kettlebell alternate floor row pause neutral grip',
        'deadball frog squat',
        'barbell bicep pulses',
        'plank diagonal reach',
    ]),
    Workout(2022, 7, 13, 'Tripledouble', [
        'battle ropes crossovers',
        '5 x double foot mountain climbers + 2 x lateral shoot throughs',
        'cone lateral step 6 x 6 fast feet',
        'shuttle sprint + 3 x squat jumps',
        '5 x deadball slam + 2 x burpee',
        'medicine ball russian twist with one arm push up',
        'box jumps jumping over',
        '10 x frog squats + 2 x sprawls',
        'kettlebell single arm swing into high pulls',
    ]),
    Workout(2022, 7, 14, 'Romans', [
        'barbell zercher squat',
        'revo double alternate staggered deadlift',
        'power bands track side walks',
        'kettlebell deadlift pause',
        'activation bands dumbbell goblet squat',
        'slides reverse lunge',
        'ybell double clean + squat outer grip',
        'soft box single leg sandbag hip thruster',
        'balance trainer crunch',
    ]),
    Workout(2022, 7, 15, 'T10', [
        'ski erg standing alternate arm pulls',
        'chin up mixed grip',
        'ybell single sprawl',
        'deadball lying chest press',
        'bike erg standing',
        'kettlebell sumo deadlift',
        'soft box 10 x high knees box jump',
        'dumbbell stationary lunge',
        'step trainer jump on-off + 4 x shuffle',
        'revo reverse curl',
    ]),
    Workout(2022, 7, 16, 'Westhollywood', [
        '10 x high knees + 2 x push ups',
        'deadball around the worlds into burpee combo',
        'plate snatch',
        'ybell squat pulses under grip',
        'power band high rear delt fly',
        'medicine ball circle + 45 degree lunges',
        'ybell single rack squat jump outer grip',
        'cone 10 x fast feet + 2 x burpee each side',
        'downward dog knee touches',
        'sandbag duck walk',
        'step trainers (x2) 180 jump',
        'rowing machine',
        'rowing machine',
        '10 x lateral shoot throughs + 2 x explosive push ups',
        'revo shoulder press',
        'barbell bent over row wide grip pause',
        'plate single leg deadlift',
        'deadball sumo squat',
        'revo front raise',
        'bike seated',
        'bike seated',
        'cone lateral hop',
        'frozen v sit',
        'dumbbell alternate forward lunge',
        'deadball overhead slams',
        'sled',
        'sled push',
    ]),
    Workout(2022, 7, 17, 'Pegasus', [
        'dumbbell bench pull overs',
        'barbell romanian deadlift + underhand grip row',
        'ybell double alternate reverse lunge outer grip',
        'suspension trainer archer push ups',
        'sandbag sumo squat',
        'dumbbell crucifix curl',
        'ybell single crunch + extension',
        'box dumbbell step up',
        'power band shoulder press',
        'kettlebell double clean + press',
        'plate overhead walking lunge',
        'barbell windscreen wipers',
        'yogy push up',
        'flutter kick',
        'staggered squat jump',
    ]),
    Workout(2022, 7, 18, 'Templars', [
        'dumbbell speed sumo squat + bicep curl',
        'push up + shoulder touch partnered',
        'bicycle ab crunch',
        'step trainer lateral hops + reverse shuffle',
        'kettlebell swing partnered',
        '10 x dumbbell punches + 2 x star jumps',
        'sledgehammer torture',
        'ladder ikky shuffle partnered',
        '10 x frog squats + 2 x squat jumps',
        'bike seated partnered',
        'medicine ball 2 x russian twists + 1 jackknives partnered',
        '10 x a-steps + 2 x burpees',
        'rowing machine partnered',
        'deadball over shoulder throw partnered',
    ]),
    Workout(2022, 7, 19, 'Piston', [
        'plate hip thruster',
        'dumbbell incline bench chest fly pause',
        'dumbbell front squats',
        'chin up underhand grip tempo 4-0-1',
        'deadball combo squat curl + press',
        'ab crunch and twist',
        'push up low pulse',
        'revo romanian deadlift alternate single leg tempo 4-0-1',
        'ybell double renegade row',
        'kettlebell step trainer alternate reverse lunge tempo 4-0-1',
        'sandbag bicep curl pulse',
        'ab wheel',
    ]),
    Workout(2022, 7, 20, 'Tripledouble', [
        'battle ropes big leaps and bounds',
        '5 x sprawls + 2 x seal jacks',
        'agility box half court squats',
        'ladder deadball with carry',
        'balance trainer jump on off + hands on burpee',
        'medicine ball knee a step + shuffle',
        'soft box depth drop + step up',
        'kettlebell swing moving side steps',
        'ybell plyo lunge pulse + punch under grip',
    ]),
    Workout(2022, 7, 21, 'Romans', [
        'balance trainer dumbbell chest press',
        'dumbbell bench incline bicep curls',
        'high plank + shoulder touch',
        'chins overhand grip 1 and half rep',
        'ybell double push press centre grip',
        'plate tricep extension',
        'kettlebell alternate floor row wide grip',
        'plate double shoulder 3 way combo',
        'swiss ball push up',
    ]),
    Workout(2022, 7, 22, 'T10', [
        'bike erg seated',
        'barbell romanian deadlift',
        'medicine ball overhead shuffle',
        'box hand stand push up',
        'ski erg explosive',
        'kettlebell upright row',
        'deadball heavy front push',
        'ybell double step trainer bulgarian',
        'soft box jumps + hands off burpee',
        'dumbbell bicep curl',
    ]),
    Workout(2022, 7, 23, 'Westhollywood', [
        'plate double front raise',
        'kettlebell push up + sumo deadlift high pull',
        'kettlebell conventional deadlift pause',
        'dumbbell step trainer alternate reverse lunge',
        'revo standing tricep extension',
        '5 x deadball squat clean + 2 x seal jack',
        'agility box hurdle double hurdle jump + back pedal',
        '5 x star jumps + lateral fast feet',
        'burpee single leg push up',
        'body weight plank elbow to knees',
        'sandbag clean + jump',
        'bike climb',
        'bike climb',
        '5 x double foot mountain climbers + 2 x inchworms',
        'dumbbell bench arnold press',
        'dumbbell t bar row',
        'cones sandbag agility power overhead cleans',
        'sandbag alternate staggered front squat',
        'ybell double bicep curl twist + squat centre grip',
        'rowing machine',
        'rowing machine',
        'agility box lateral runs',
        '5 x sprawl + 2 x seal jack',
        'box dumbbell man killer step ups',
        'balance trainer 10 x mountain climber and overhead press',
        'sled burpee power push',
        'slides bear crawl to reverse bear crawl',
    ]),
    Workout(2022, 7, 24, 'Pegasus', [
        'dumbbell alternate floor press',
        'barbell sumo deadlift',
        'suspension trainer chest hugs row hug cross over',
        'ybell double pick up + hammer curl centre grip',
        'barbell front squat + shoulder press + squat press',
        'balance trainer plank + alternate knee to elbow',
        'dumbbell bench close grip tricep press',
        'sandbag alternate staggered deadlift',
        'power band seated close grip row',
        'revo dead bug',
        'deadball squat cleans',
        'plate straight arm twists',
        'yogy push up',
        'flutter kicks',
        'staggered squat jump',
    ]),
    Workout(2022, 7, 25, 'Redline', [
        'ski erg explosive',
        'ybell single alternate clean + lunge',
        'shuttle sprint with lateral jumps',
        'balance trainer 10x mountain climbers 5x in out jumps',
        'bike erg seated',
        'suspension trainer alternate row x4 + squat',
        'soft box jump + squat',
        '10 x bicycle kicks + 5 x leg raises',
        'skipping',
    ]),
    Workout(2022, 7, 26, 'Thenines', [
        'revo step trainer bulgarian // revo back sumo squat',
        'barbell romanian deadlift // leg raises',
        'kettlebell alternate floor row neutral grip // kettlebell burpee + push up',
        'dumbbell goblet squats // dynamic frog squat',
        'balance trainer dumbbell chest fly // balance trainer diamond push up',
        'suspension trainer neutral grip row // suspension trainer rear delt raise',
        'ybell double rack press outer grip // ybell double hammer curl centre grip',
        'dumbbell flat bench press // bench tricep dips',
        'bike climb // bike climb',
    ]),
    Workout(2022, 7, 27, 'Athletica', [
        '10 x dumbbell punches + 2 x squat and press',
        'explosive crouch starts 5 each side',
        'kettlebell swing',
        'rowing machine',
        'box jump',
        'cone 10 x fast feet + 2 x seal jack each side',
        'bike standing',
        'agility box hurdle forward hurdle jump + back pedal',
        'ybell devil press',
    ]),
    Workout(2022, 7, 28, 'Mkatz', [
        'dumbbell sumo deadlift',
        'ybell circle + 45 degree lunge',
        'activation band soft box hip thruster',
        'kettlebell racked sumo squat',
        'balance trainer supine single leg bridge',
        'suspension trainer pistol squat pulse',
        'barbell romanian deadlift',
        'plate overhead reverse lunge',
        'dumbbell racked farmers walk',
    ]),
    Workout(2022, 7, 29, 'Miaminights', [
        'battle ropes crossovers',
        'balance trainer burpee + shoulder press',
        '5 x deadball slam + 2 x squat jumps',
        'ybell double clean outer grip',
        'chin up underhand grip pause',
        'dumbbell flat bench chest fly pause',
        'sandbag romanian deadlift pause',
        'barbell zercher squat pause',
        'triple switch hold + 5 x ice skater',
        'burpee side',
        'frog squats x3 + plyo lunge x4',
        'hand walks in and hand walks out',
    ]),
    Workout(2022, 7, 30, 'Specialopshollywood', [
        'balance trainer reverse burpees',
        'dumbbell curtsey squat + curl',
        'bike hover',
        'agility box hurdle u line shuffle',
        'box jump + burpee',
        '5 x deadball slam + 2 x seal jack',
        '10 x wide mountain climber + 2 x frog squat',
        'dumbbell glute bridge tri extension',
        'ski erg explosive',
        'ybell double tricep sprawl top grip',
        'dumbbell alternate single push press',
        'deadball headlock squats 3x3',
        'amrap: 5 x speed sprawls // 10 x speed squats // 20 x flutter kick',
    ]),
    Workout(2022, 7, 31, 'Wingman', [
        'deadball bent over row',
        'power band low rear delt fly',
        'dumbbell lateral lunge pulse',
        'dumbbell front squat + 3 second pause',
        'feet up twist crunches',
        'high plank + leg lift',
        'suspension trainer close grip row',
        'soft box explosive incline push ups',
        'activation bands balance trainer hip thruster',
        'kettlebell activation band romanian deadlift',
        'barbell push press',
        'barbell bicep curl',
        'dumbbell bench flat chest fly',
        'dive bomb push up',
        'revo sit ups',
        'revo windscreen wipers',
        'ybell single pick up cross halo transition',
        'dumbbell tricep kick backs',
    ]),
    Workout(2022, 8, 1, 'Redline'),
    Workout(2022, 8, 2, 'Thenines'),
    Workout(2022, 8, 3, 'Athletica'),
    Workout(2022, 8, 4, 'Mkatz'),
    Workout(2022, 8, 5, 'Miaminights'),
    Workout(2022, 8, 6, 'Specialopshollywood'),
    Workout(2022, 8, 7, 'Wingman'),
    Workout(2022, 8, 8, 'Redline'),
    Workout(2022, 8, 9, 'Thenines'),
    Workout(2022, 8, 10, 'Athletica'),
    Workout(2022, 8, 11, 'Mkatz'),
    Workout(2022, 8, 12, 'Miaminights'),
    Workout(2022, 8, 13, 'Heroeshollywood'),
    Workout(2022, 8, 14, 'Wingman'),
    Workout(2022, 8, 15, 'Redline'),
    Workout(2022, 8, 16, 'Thenines'),
    Workout(2022, 8, 17, 'Athletica'),
    Workout(2022, 8, 18, 'Mkatz'),
    Workout(2022, 8, 19, 'Miaminights'),
    Workout(2022, 8, 20, 'Specialopshollywood'),
    Workout(2022, 8, 21, 'Wingman'),
];

let workoutStyleList = [
    ...new Set(workoutsByDate.map(workout => workout.displayStyle)),
].sort();

function getWorkoutByDate(date: Date) {
    const datesMatch = (date1: Date, date2: Date) => date1.getDate() === date2.getDate();
    const monthsMatch = (date1: Date, date2: Date) => date1.getMonth() === date2.getMonth();
    const yearsMatch = (date1: Date, date2: Date) =>
        date1.getFullYear() === date2.getFullYear();
    const areDatesEqual = (date1: Date, date2:Date) =>
        datesMatch(date1, date2) &&
        monthsMatch(date1, date2) &&
        yearsMatch(date1, date2);

    return workoutsByDate.find(workout => areDatesEqual(
                new Date(workout.year, workout.month - 1, workout.date),
                date
            )
        );
}

const getLastWorkoutByStyle = displayStyle =>
    workoutsByDate
        .filter(workout => workout.displayStyle === displayStyle)
        .sort((workoutA, workoutB) => workoutA.date - workoutB.date)
        .pop();

export {
    // aircraftList,
    // getAcftById,
    // getHeaviestAndMostForward,
    // instructorList,
    // getInstById,
    workoutStyleList,
    workoutsByDate,
    getWorkoutByDate,
    getLastWorkoutByStyle,
};
